include: ../analysis_options.yaml

analyzer:
  errors:
    # Allow print statements in stub implementations for development visibility
    avoid_print: ignore
    # Stub implementations intentionally store injected dependencies for future use
    unused_field: ignore
